<?php
/** @var \BelVG\Showroom\Block\Booking $block */
$customer = $block->getCustomer();
?>
<div class="block showroom">
    <div class="title"><strong><?= $block->escapeHtml(__('Showroom Booking')) ?></strong></div>
    <div class="content">
        <form class="form booking"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id = "showroom-validate-detail">
            <div class="fieldset">
                <div class="field">
                    <div class="control">
                        <input name="customer_name" type="text" id="booking-name"
                               placeholder="<?= $block->escapeHtml(__('Enter your name')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               value="<?= $customer ? $customer->getName() : '' ?>"
                        />
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input name="customer_email" type="email" id="booking-email"
                               placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                               value="<?= $customer ? $customer->getEmail() : '' ?>"
                        />
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <input name="booking_date" type="date" id="booking-date"
                               placeholder="<?= $block->escapeHtml(__('Enter date')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'"
                        />
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        <select id="select-showroom" name="showroom_name" title="<?= $block->escapeHtmlAttr(__('Showroom')) ?>" class="showroom">
                            <?php if ($showrooms = $block->getShowrooms()): ?>
                                <?php foreach ($showrooms as $showroom) : ?>
                                    <option value="<?= $showroom['showroom_name'] ?>">
                                        <?= $block->escapeHtml($showroom['showroom_name']) ?>
                                    </option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>
                <div class="actions">
                    <button class="action showroom primary"
                            title="<?= $block->escapeHtmlAttr(__('Book')) ?>"
                            type="submit"
                            aria-label="Book">
                        <span><?= $block->escapeHtml(__('Book')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "showroom-validate-detail"
            }
        }
    }
</script>
